name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'chatbot/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd chatbot
        npm ci
    
    - name: Run linting
      run: |
        cd chatbot
        npm run lint || echo "Linting issues found"
    
    - name: Run tests
      run: |
        cd chatbot
        npm test -- --watchAll=false
    
    - name: Build
      run: |
        cd chatbot
        npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: chatbot/dist/

  # デプロイジョブは必要に応じて追加
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-output
  #         path: .next
  #     
  #     - name: Deploy to production
  #       run: echo "デプロイコマンドをここに記述" 